name: "build"
on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghrc.io # Image registry, ghcr.io incase of GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Automated Version Bump
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          tags: ${{ env.IMAGE_NAME }}:latest, ${{ env.IMAGE_NAME }}:${{ steps.version-bump.outputs.newTag }}
